version: '2.1'


services:

  master-filebeat:
    extends:
      file: docker-compose.yml
      service: master-filebeat

  logstash:
    extends:
      file: docker-compose.yml
      service: logstash

  validate-logstash-config:
    extends:
      file: docker-compose.yml
      service: validate-logstash-config

  elasticsearch:
    extends:
      file: docker-compose.yml
      service: elasticsearch
    ports:
      - ${ELASTICSEARCH_HOST_PORT:-9200}:9200

  curator:
    extends:
      file: docker-compose.yml
      service: curator

  kibana:
    extends:
      file: docker-compose.yml
      service: kibana
    ports:
      - ${KIBANA_HOST_PORT:-5601}:5601

  elastalert:
    extends:
      file: docker-compose.yml
      service: elastalert

networks:
  default:
    external:
      name: monitoring_logging



