version: '2.1'


services:

  master-filebeat:
    extends:
      file: docker-compose.yml
      service: master-filebeat

  logstash:
    extends:
      file: docker-compose.yml
      service: logstash

  validate-logstash-config:
    extends:
      file: docker-compose.yml
      service: validate-logstash-config

  elasticsearch:
    extends:
      file: docker-compose.yml
      service: elasticsearch

  curator:
    extends:
      file: docker-compose.yml
      service: curator

  kibana:
    extends:
      file: docker-compose.yml
      service: kibana
    environment:
      - VIRTUAL_HOST=kibana.${DOMAIN}
      - LETSENCRYPT_HOST=kibana.${DOMAIN}
      - LETSENCRYPT_EMAIL=admin@${DOMAIN}
      - LETSENCRYPT_TEST=false
      - HTTPS_METHOD=nohttp

  elastalert:
    extends:
      file: docker-compose.yml
      service: elastalert

networks:
  default:
    external:
      name: monitoring_logging



