version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    volumes:
      - ./datadir:/data/db
    ports:
      - '27017:27017'

  rabbitmq:
    image: rabbitmq
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
