version: '3'
services:
  mongo0:
    hostname: mongo0
    container_name: mongo0
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./datadir/datadir0:/data/db
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - ./datadir/datadir1:/data/db
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo
    ports:
      - 27019:27017
    volumes:
      - ./datadir/datadir2:/data/db
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongo-rs0-setup:
    container_name: "mongo-rs0-setup"
    image: mongo
    depends_on:
      - "mongo0"
      - "mongo1"
      - "mongo2"
    links:
      - mongo0:mongo0
      - mongo1:mongo1
      - mongo2:mongo2
    volumes:
      - ./scripts:/scripts
    environment:
      - MONGO0=mongo0
      - MONGO1=mongo1
      - MONGO2=mongo2
      - RS=rs0
    entrypoint: [ "/scripts/setup.sh" ]

  rabbitmq:
    image: rabbitmq
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
