version: '3.3'
services:
  rs1:
    image: mongo:4.0
    command: mongod --replSet "rs0"
    networks:
      - backend
  rs2:
    image: mongo:4.0
    command: mongod --replSet "rs0"
    networks:
      - backend

  rs3:
    image: mongo:4.0
    command: mongod --replSet "rs0"
    networks:
      - backend

  rs:
    image: naviat/mongors
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"
      - "15672"
    networks:
      - backend

  server:
    image: backend
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8080"
    networks:
      - backend
    depends_on:
      - rs1
      - rs2
      - rs3
      - rabbitmq

#volumes:
#  db-data:

networks:
  backend:
    external: true
