version: '3.3'
services:
  rs1:
    image: mongo
    command: mongod --replSet "rs0"
    ports:
      - "27017:27017"
    volumes:
      - db-data-1:/data/db
    networks:
      - backend
  rs2:
    image: mongo
    command: mongod --replSet "rs0"
    ports:
      - "27017:27017"
    volumes:
      - db-data-2:/data/db
    networks:
      - backend

  rs3:
    image: mongo
    command: mongod --replSet "rs0"
    ports:
      - "27017:27017"
    volumes:
      - db-data-3:/data/db
    networks:
      - backend

  rs:
    image: naviat/mongors
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"
      - "15672"
    networks:
      - backend

  server:
    image: backend
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - config:/config
    ports:
      - "8080"
    networks:
      - backend
    depends_on:
      - rs1
      - rs2
      - rs3
      - rabbitmq

volumes:
  db-data-1:
  db-data-2:
  db-data-3:

networks:
  backend:
    driver: overlay
    external: true
