version: "3"

networks:
  proxy:
    external: true
  internal:

services:
  traefik:
    container_name: traefik
    image: traefik:1.7.4-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:monitor.example.org
      - traefik.port=8080
    networks:
      - proxy
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/traefik.toml
      - $PWD/acme.json:/acme.json

  web:
    container_name: web
    image: nginx:1.15.7-alpine
    restart: always
    labels:
      - traefik.backend=web
      - traefik.frontend.rule=Host:example.org
      - traefik.port=80
    networks:
      - internal
    depends_on:
      - frontend
      - backend
      - database
    volumes:
      - $PWD/nginx.conf:/etc/nginx/conf.d/default.conf
      - $PWD/app:/usr/share/nginx/html
